// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyotaGarancneOpravy.Models;

#nullable disable

namespace ToyotaGarancneOpravy.Migrations
{
    [DbContext(typeof(Toyota_DBContext))]
    [Migration("20220419081930_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToyotaGarancneOpravy.Models.GarancnaOprava", b =>
                {
                    b.Property<int>("GarancnaOpravaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarancnaOpravaId"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cws")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Protokol")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TbFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("TbScan")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TgFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("TgScan")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Vin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZakazkaTb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZakazkaTg")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GarancnaOpravaId");

                    b.ToTable("GarancnaOprava");
                });

            modelBuilder.Entity("ToyotaGarancneOpravy.Models.Priloha", b =>
                {
                    b.Property<int>("PrilohaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrilohaId"), 1L, 1);

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GarancnaOpravaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrilohaFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrilohaNazov")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PrilohaSubor")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("PrilohaTyp")
                        .HasColumnType("int");

                    b.Property<int?>("PrilohaTypNavigationPrilohaTypId")
                        .HasColumnType("int");

                    b.HasKey("PrilohaId");

                    b.HasIndex("GarancnaOpravaId");

                    b.HasIndex("PrilohaTypNavigationPrilohaTypId");

                    b.ToTable("Priloha");
                });

            modelBuilder.Entity("ToyotaGarancneOpravy.Models.PrilohaTyp", b =>
                {
                    b.Property<int>("PrilohaTypId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrilohaTypId"), 1L, 1);

                    b.Property<int?>("Aktivna")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateddBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrilohaNazov")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrilohaPopis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PrilohaTypId");

                    b.ToTable("PrilohaTyp");
                });

            modelBuilder.Entity("ToyotaGarancneOpravy.Models.Priloha", b =>
                {
                    b.HasOne("ToyotaGarancneOpravy.Models.GarancnaOprava", "garancnaOprava")
                        .WithMany("Prilohy")
                        .HasForeignKey("GarancnaOpravaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaGarancneOpravy.Models.PrilohaTyp", "PrilohaTypNavigation")
                        .WithMany("Prilohy")
                        .HasForeignKey("PrilohaTypNavigationPrilohaTypId");

                    b.Navigation("PrilohaTypNavigation");

                    b.Navigation("garancnaOprava");
                });

            modelBuilder.Entity("ToyotaGarancneOpravy.Models.GarancnaOprava", b =>
                {
                    b.Navigation("Prilohy");
                });

            modelBuilder.Entity("ToyotaGarancneOpravy.Models.PrilohaTyp", b =>
                {
                    b.Navigation("Prilohy");
                });
#pragma warning restore 612, 618
        }
    }
}
